name: Deploy to S3

on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
    timeout-minutes: 10
    steps:
        - name: Deploy
          uses: reggionick/s3-deploy@v3
          with:
            folder: client
            bucket: ${{ secrets.S3_BUCKET }}
            bucket-region: us-west-2
            dist-id: ${{ secrets.CLOUDFRONT_DISTRIBUTION_ID }}
            invalidation: /
            delete-removed: false
            no-cache: true
            private: false
            filesToInclude: ".*/*,*/*,**"
